### ISSUE TITLE
Group clause

### ISSUE THREAD

**Issue by ptbrowne** [tpluscode/sparql-builder#57]
Hi, I need support for the Group clause to be able to count datasets pertaining to a particular organisation/theme, is it something that could be added here ? Would you be open to a PR if I manage to add it ?

**Comment by tpluscode** [comment]
Of course, I totally intended to add `GROUP BY` but haven't had the need yet.

Please try `0.3.17`

**Comment by ptbrowne** [comment]
Thanks for the quick response ! I'll try it out tomorrow :)

**Comment by ptbrowne** [comment]
It worked perfectly, thanks @tpluscode
