### ISSUE TITLE
Auto prefixing and nested sparql tokens

### ISSUE THREAD

**Issue by ptbrowne** [tpluscode/sparql-builder#62]
I have a usecase where I am building a sparql query from filters. Here is a contrived example:

```
const { SELECT, sparql } = require("@tpluscode/sparql-builder");
const { schema } = require("@tpluscode/rdf-ns-builders");

const filters = ["a"];
const query = SELECT.DISTINCT`?value`.WHERE`
    ${filters.map((f) => `FILTER (( ${schema.sameAs} = 1 )`)}
  `;

console.log(query.build());
```

The result is:

```
SELECT DISTINCT ?value

WHERE {

    FILTER (( [object Object] = 1 )
  
}
```

Supposedly, the "nested" template string tokens are not detected by the query builder, so they cannot be transformed to string and their prefix is not added to the beginning of the query.

1. How can I deal with nested template strings ?
2. One other way to deal with this would be to `toString({prologue:false})` the sparql token myself but I would need to add the prefix manually to the query afterwards, is it possible ?

At the moment I have used `<https://schema.org/sameAs>` directly in my query.

**Comment by tpluscode** [comment]
The inner string must be tagged. I notice that you actually import `sparql` but forgot to use it?

```diff
-   ${filters.map((f) => `FILTER (( ${schema.sameAs} = 1 )`)}
+   ${filters.map((f) => sparql`FILTER (( ${schema.sameAs} = 1 )`)}
```

**Comment by ptbrowne** [comment]
Nice 🎉  I had used it but wrongly.

This is wrong:

```
const query = SELECT.DISTINCT`?value`.WHERE`
    ${filters.map(
      (f) =>
        `FILTER (( ${sparql`schema.sameAs`}) = 1 )`
    )}
  `;
```

**Comment by ptbrowne** [comment]
Thanks for the super quick response !

**Comment by tpluscode** [comment]
You're welcome :)
