### ISSUE TITLE
Use @rdfjs rather than @rdfjs-esm

### ISSUE THREAD

**Issue by jeswr** [tpluscode/sparql-builder#88]
Installing this package results in the following warnings:

```
npm WARN deprecated @rdf-esm/to-ntriples@0.5.0: Use @rdfjs/to-ntriples
npm WARN deprecated @rdf-esm/to-ntriples@0.6.0: Use @rdfjs/to-ntriples
```

Which appears to be from its dependence on `@rdfjs-esm/term-set` and `@rdfjs-esm/data-model` rather than `@rdfjs/term-set` and `@rdfjs/data-model`.

**Comment by tpluscode** [comment]
Hey. Maybe I was a little too hasty or imprecise with these deprecations...

I created the `@rdf-esm/*` packages to have dual CommonJS/ESM RDF packages. With `@rdfjs/*` are either CJS (`v1.*`) or ESM (`v2`).

In the long run (not that long, hopefully), I do intend to make all my code ESM-only at which point I will be ready to switch to latest `@rdfjs` and kill the `@rdf-esm` forks altogether

**Comment by tpluscode** [comment]
As of v1, only `@rdfjs/*` packages are used
